//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWG.Infrastructure.Dal.Impl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EWG.Infrastructure.Dal.Impl.DatabaseScripts", typeof(DatabaseScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[DicGenericDictionaryItems] (discriminator, name, resourceName, publicCode, dateStart, dateEnd)
        ///
        ///VALUES
        ///	(N&apos;GameMode&apos;, N&apos;gameMode00&apos;, N&apos;gameMode00&apos;, N&apos;0&apos;, GETDATE(), null),
        ///	(N&apos;GameMode&apos;, N&apos;gameMode01&apos;, N&apos;gameMode01&apos;, N&apos;1&apos;, GETDATE(), null),
        ///	(N&apos;GameMode&apos;, N&apos;gameMode02&apos;, N&apos;gameMode02&apos;, N&apos;2&apos;, GETDATE(), null),
        ///	
        ///	(N&apos;GameType&apos;, N&apos;gameType00&apos;, N&apos;gameType00&apos;, N&apos;0&apos;, GETDATE(), null),
        ///	(N&apos;GameType&apos;, N&apos;gameType01&apos;, N&apos;gameType01&apos;, N&apos;1&apos;, GETDATE(), null),
        ///	(N&apos;GameType&apos;, N&apos;gameType02&apos;, N&apos;ga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertDictionariesScript {
            get {
                return ResourceManager.GetString("InsertDictionariesScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*==============================================================*/
        ////* DBMS name:      Microsoft SQL Server 2008                    */
        ////* Created on:     08.03.2015 16:51:23                          */
        ////*==============================================================*/
        ///
        ///
        ///if exists (select 1
        ///   from sys.sysreferences r join sys.sysobjects o on (o.id = r.constid and o.type = &apos;F&apos;)
        ///   where r.fkeyid = object_id(&apos;Players&apos;) and o.name = &apos;FK_PLAYER_REF_PLAYERUSER&apos;)
        ///alter table Players
        ///   drop constraint FK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewDbScript {
            get {
                return ResourceManager.GetString("NewDbScript", resourceCulture);
            }
        }
    }
}
